### ISSUE TITLE
【BUG】补杠显示Bug

### ISSUE THREAD

**Issue by Zweo** [ailab-pku/botzone-local#2]
例子：
![image](https://user-images.githubusercontent.com/19181921/113966082-0babf300-9861-11eb-8f7f-d87c9443b94a.png)

报错信息：
TypeError: '<' not supported between instances of 'NoneType' and 'str'

定位是这里：
display部分的render函数里面
![image](https://user-images.githubusercontent.com/19181921/113967110-ecae6080-9862-11eb-97d6-e3d6ae9b6d83.png)

应该是补杠时self.hand的处理有问题。

**Comment by castor-v-pollux** [comment]
多谢，我这两天会跑个详细的测试把这个播放器的bug都找到修一下

**Comment by castor-v-pollux** [comment]
播放器在抢杠和的时候会出现这个bug，已修复；另外用五位数的对局测试了播放器，现在应该没有bug了
